---
- name: Install which (needed by flux installer)
  community.general.pacman:
    name: which
    state: present

- name: Install Flux CLI
  shell: curl -s https://fluxcd.io/install.sh | bash
  args:
    creates: /usr/local/bin/flux
